### ISSUE TITLE
Document (breaking) changes between v0.1 and v0.2?

### ISSUE THREAD

**Issue by nstiurca** [JuliaData/XML.jl#13]
I wrote some code against v0.1 which had something like `myFunction(doc::XML.Document) = <...>`. But trying to upgrade to v0.2 of XML, I get the mysterious error `ERROR: LoadError: ArgumentError: invalid type for argument doc in method definition for myFunction at <file>:<line>`. Any idea what's going on? I added a compat entry for my package for now to stay on XML v0.1.

I'm getting this error on both julia 1.8 and 1.9.

**Comment by joshday** [comment]
There are some big breaking changes between the two versions that:

1) Are necessary for performance reasons.
2) Are impossible to deprecate cleanly.

---

The new way of doing things is in the README, but here's a summary:

1) The previous structs have been removed and their names have been reused in an enum type.  The cryptic error you're seeing is because `Document` is no longer a type, but instead is an instance of the enum type `NodeType`.  

2) Most of the old syntax still works, e.g. `Document(children...)`.

3) Your function would now need to be something like:


```julia
function myfunction(node::Node)
    nodetype(node) == Document || error("myfunction requires a Document input")
    <...>
end

```


I hope this helps! Stick to v0.1 if you need the individual structs and open another issue if v0.2 is making something harder to accomplish.

**Comment by nstiurca** [comment]
Thanks a lot!

Yeah, totally fair to upend your data structures between v0.1 and v0.2 without "clean" deprecation.
